version: '3.3'
services:
  webapp:
    image: driversweb-image:latest 
    container_name: driverse-webapp1
    ports:
      - "3000:3000" 
    command: ["npm", "start"]

  nginx1:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" 
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/app/public
    depends_on:
      - webapp


networks:
  default:
    driver: bridge
