version: '3.3'
services:
  webapp:
    image: driversweb-image:latest
    container_name: drivers-webapp
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - webapp 
