server {
    listen 80;
    server_name driverse.ai;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name driverse.ai;

    # SSL Certificate and Key (temporary values, will be replaced by Certbot)
    ssl_certificate /etc/ssl/certs/ssl-bundle.crt;
    ssl_certificate_key /etc/ssl/private/ssl.key;

    location / {
        proxy_pass http://webapp:3000;  # Proxy to webapp
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
